### ISSUE TITLE
Questions about Yubikey and Mifare cards (and more)

### ISSUE THREAD

**Issue by mmm4m5m** [jenspfahl/ANOTHERpass#17]
Do you plan to support Mifare cards with encryption? Or maybe yubikey?

QR code can be easily copied and stolen. Regular NFC tags can be quickly read and clonned - NFC tags without encryption.

I used to trust Smart Lock with bluetooth handsfree, but looks like, that is even more easy to crack compared to NFC and QR code. (Bluetooth communication can be sniffed from big distance and I assume that device MAC can be easify clonned).

Thank you.

---

For NFC tag, there could be (daily/weekly) reminder - "change and write new master password to NFC tag" (because write is easy and quick)

---

For NFC tag, there could be "counter" - after unlock, increase the counter and write it to NFC tag. This could be useful if someone clone/copy your NFC tag.

---

There could be a log - "last vault unlocks", "last viewed passwords". If codeword is used for the master password, then the log could be hidden without the codeword.

**Comment by jenspfahl** [comment]
Hey! 
I don't have concrete plans to support Mifare or Yubikey, but i was thinking about integrating Yubikey somewhen. I am not familiar with Mifare and how to integrate but with Yubikey i could imagine to push a private key generated by the app and use HMAC to authorize (as alternative to the Master Password Token). What i read about Mifare is they use a proprietary encryption which is actually broken by CCC.

Yes QR codes and NFC tags can quickly be copied, therefore the Exported Master Password (EMP) can be protected with a codeword. Normally, these should be kept at a safe place. But for the Master Password Token (MPT) you are right, this is indeed risky. A reminder to renew it regularly is definitely a good idea!

About incrementing a counter on the MPT tag is imho not appropriate to protect against copying. An attacker could copy the token and use it before i use it and it will let the attacker in, so no win. But i am currently working on the next version of the app including another copy protection for these tokens. Since each NFC tag has its unique static Id, the app will just save this Id and only accepts tokens from NFC tags with this Id. But this doesn't work for tokens on QR codes, so in this case the app will decline tokens from QR codes.   
 
v1.6.2 still shows a prompting notification while login when a previous login was unsuccessful. So the user could recognize unauthorized login attempts. The prompt can also show the last successful login if configured in the settings.

**Comment by mmm4m5m** [comment]
@jenspfahl  Thanks. 

About NFC with counter - if attacker use the NFC token before you, then it will be alert for you - NFC token is compromised. (I did not know about "failed login" notification)

About Mifare - it is NFC card with encryption. That makes it harder to copy/clone. You need the keys to read and write encrypted NFC card. 

For example, Google knows how to crack Mifare classic 1k, the most simple case. For that the attacker will needs 2 hours and the best equipment. (With regular card reader he will needs 2 days). 

There are other encrypted card types offering better security - S7, Desfire. I do not know details.

**Comment by jenspfahl** [comment]
Thanks for pointing me to metrodroid. It is quite impressing how much kind of cards they support and how they collect all the details to read them! But I don't think I would integrate any of these cards into the app unless it is requested by more people. It looks very complex to do so. But the proposal to use a Yubikey sounds interesting to me and I have already planned to buy one for a long time, let's see.
