### ISSUE TITLE
Importing from Google passwords 

### ISSUE THREAD

**Issue by iplayradionetworks** [jenspfahl/ANOTHERpass#18]
Hi 

Is there a method to import credentials from Google passwords?

Best regards
Jim

**Comment by jenspfahl** [comment]
Not at the moment, but maybe this could be a feature for future releases. I could imagine a function to import CSV or JSON files exported from stored passwords of browsers like Firefox or Chrome.

**Comment by iplayradionetworks** [comment]
> Not at the moment, but maybe this could be a feature for future releases. I could imagine a function to import CSV or JSON files exported from stored passwords of browsers like Firefox or Chrome.

..... 
It would be really awesome as I have plenty passwords in google passwords system which I no longer want to have there .... I don't trust google for many reasons.  

I am willing to contribute if you can build this function in a future update version. 

Lastly I am interested in translation of the app. I have translated many others too. 

Best regards
Jim

**Comment by jenspfahl** [comment]
I thought about it and I think it is doable. I am still working on the next release anyway so I can add this functionality. I would provide a new Import menu entry to import any kind of CSV files first, since passwords from browsers are usually exported as CSV. Such CSVs consist mainly of a name, an url, a username and the plain password. So after parsing the file it should be easy to import the credentials to the vault.

Translators are welcome! I had a hard time to translate the whole strings.xml into German so I would very appreciate other languages!

**Comment by iplayradionetworks** [comment]
> I thought about it and I think it is doable. I am still working on the next release anyway so I can add this functionality. I would provide a new Import menu entry to import any kind of CSV files first, since passwords from browsers are usually exported as CSV. Such CSVs consist mainly of a name, an url, a username and the plain password. So after parsing the file it should be easy to import the credentials to the vault.
> 
> Translators are welcome! I had a hard time to translate the whole strings.xml into German so I would very appreciate other languages!

That's cool. Ok then. So I shall wait for next version ☺️. 

As for the strings.xml you can always send it via email or perhaps attach it here ? I can translate it as soon as possible. 

And I after my tests with the newer version I shall also donate for an appreciation 😉

Best regards
Jim

**Comment by jenspfahl** [comment]
Hi Jim,

i have added a new feature to import credentials from csv files (from Chrome and Firefox) for the next version (1.7.0). This version is not yet released because i want to test it a bit before but you can[ download the release candidate here](https://anotherpass.jepfa.de/app/anotherpass.apk) if you like (note, this apk is signed by me, not by F-Droid). 

Regarding the translations, which language could you provide? Here is the [strings.xml for the next release](https://raw.githubusercontent.com/jenspfahl/ANOTHERpass/rc-1.7.0/app/src/main/res/values/strings.xml) free to translate. I can also integrate translations in future releases, so no hurry.

Thanks
Jens

**Comment by iplayradionetworks** [comment]
> Hi Jim,
> 
> i have added a new feature to import credentials from csv files (from Chrome and Firefox) for the next version (1.7.0). This version is not yet released because i want to test it a bit before but you can[ download the release candidate here](https://anotherpass.jepfa.de/app/anotherpass.apk) if you like (note, this apk is signed by me, not by F-Droid). 
> 
> Regarding the translations, which language could you provide? Here is the [strings.xml for the next release](https://raw.githubusercontent.com/jenspfahl/ANOTHERpass/rc-1.7.0/app/src/main/res/values/strings.xml) free to translate. I can also integrate translations in future releases, so no hurry.
> 
> Thanks
> Jens 

Hi Jens

Amazing. I shall install this version to test import from a csv file from chrome ;)

Will keep you informed.  Here ... 

As for the strings file. Do you have an example of a translation so I can see exactly what to translate ? I will tho open the file ... I might figure it myself 😉

Regards
Jim

**Comment by iplayradionetworks** [comment]
Ok import went well. 

The great thing is for me ... Why do I have to login to my vault prior before auto suggesting or have to select the credentials I want ?

Google autofill senses the app or url I am and automatically suggests the credentials for me in the popup box ... I don't have to login first somewhere in google . 

Can that be done in your app ?

Best regards
Jim

**Comment by jenspfahl** [comment]
Well, Google seems to let the vault unlocked all the time to be able to lookup the credentials that might fit to the current open app or website.  This is not indented by my app. But you can unlock the vault and it remain it unlocked for a defined period of time, where you don't need to unlock again (configurable in the Settings/Security). 

In regards to auto-suggesting, yes, i would also like this feature. But here is a risk of exposing user names and passwords to malicious apps, when i would pass a suggested credential automatically without a prior user interaction like "Unlock" or "select a credential from the vault". This is because some malicious apps might use the same internal package name as of trusted apps and can therefore pretend to be the right receiver of a suggested autofill. So i am not sure if i want to implement such a auto-suggestion feature. But could imagine to show all suggested credentials in the app (if there any) so it is easier to find the correct one. 

All-in-all, Autofill is very complex and i am still working on it.

**Comment by iplayradionetworks** [comment]
> Well, Google seems to let the vault unlocked all the time to be able to lookup the credentials that might fit to the current open app or website. This is not indented by my app. But you can unlock the vault and it remain it unlocked for a defined period of time, where you don't need to unlock again (configurable in the Settings/Security).
> 
> In regards to auto-suggesting, yes, i would also like this feature. But here is a risk of exposing user names and passwords to malicious apps, when i would pass a suggested credential automatically without a prior user interaction like "Unlock" or "select a credential from the vault". This is because some malicious apps might use the same internal package name as of trusted apps and can therefore pretend to be the right receiver of a suggested autofill. So i am not sure if i want to implement such a auto-suggestion feature. But could imagine to show all suggested credentials in the app (if there any) so it is easier to find the correct one.
> 
> All-in-all, Autofill is very complex and i am still working on it.

Hi. Sorry for my late reply. 

Well look the way google handles the autofill is very handy as its very quick .... and yes the reason is because its unlocked. I guess i can do the same with your app.... but you could have an additional option for "leave unlocked for unlimited time" ? 

Look if the auto-detection is correct then auto-suggestion will also be just fine . I do understand your point of view regarding the malicious apps. But this is tricky.... why would anyone have a "malicious app" installed on phone ? I mean that apps that do offer password protection or banking apps or websites of course via browser that force your to login via your credentials are not malicious either. 

So i think that you have nothing to worry about regarding malicious apps. 

I wish i could describe it better .... but i hope you understand what i am trying to say here. 

Regards
Jim
